### ISSUE TITLE
大佬，docker 启动登录按钮都没了

### ISSUE THREAD

**Issue by hausen1012** [npsvip/dsback#1]
如题

**Comment by npsvip** [comment]
运行没问题的话建议更换下浏览器，可能是兼容问题

**Comment by npsvip** [comment]
用的什么浏览器？版本是新版么？目前测试mac下谷歌、safari,win10下edge、谷歌、360都是正常的

**Comment by hausen1012** [comment]
是 edge
![image](https://user-images.githubusercontent.com/50026605/189863987-60bfe0cc-8493-41df-9ef7-1c1d17b960bd.png)

**Comment by hausen1012** [comment]
换谷歌正常了
