### ISSUE TITLE
docker 安装后，一直重启，没有日志也不清楚什么原因

### ISSUE THREAD

**Issue by xbo729** [npsvip/dsback#3]
如题

**Comment by xbo729** [comment]
![image](https://user-images.githubusercontent.com/13294849/189570716-32d1d907-81cd-4347-bedc-d7b1e7d91294.png)
服务器DDos阈值保存不了

**Comment by npsvip** [comment]
启动不成功一般是数据库配置错了，你这个截图可能压根就没安装好或者服务器连接不上
