### ISSUE TITLE
mysql5.1.73

### ISSUE THREAD

**Issue by solitaryfan** [npsvip/dsback#4]
我对于mysql5.1.73有特殊的需求，本人也是个小白，很希望能有兼容5.1.73的sql或能有一键命令生成数据库表

**Comment by npsvip** [comment]
好的，后面增加兼容测试

**Comment by npsvip** [comment]
已经增加了兼容，但是我找不到5.1的mysql，5.5测试下已经兼容，应该可以了，可以试一下

**Comment by npsvip** [comment]
已经增加了兼容，但是我找不到5.1的mysql，5.5测试下已经兼容，应该可以了，可以试一下
